### ISSUE TITLE
Export annotation

### ISSUE THREAD

**Issue by Ahuriste** [neuralmagic/sparseml#1028]
Hello,

I'm currently working on sparsification/quantization of yolov5 using sparseml. I have my optimized model. I would like to run inference on images and to export the result in a txt file like yolo does. Is it possible with `deepsparse.object_detection.annotate `?

Thank you

**Comment by dbogunowicz** [comment]
Hey @Ahuriste 

Good question. 

The easiest thing to do would be running inference using the deep sparse server. The request basically holds all the relevant output, that you'd probably like to then dump into a text file. 

If you insist on using the `annotate` script, what I can currently suggest to you is slightly tweaking the source code to accommodate your needs. See those three variables here: `boxes`, `scores`, `labels` here: https://github.com/neuralmagic/deepsparse/blob/main/src/deepsparse/yolo/utils/utils.py#L447
This is the data that should interest you in every inference pass. It should be quite easy to modify the script so that in every inference pass all this data gets saved/appended to a text file.

Hopefully, this helps. If you need more detailed information, feel free to ping me here.
