### ISSUE TITLE
The dense training of yolov8n-seg failed!

### ISSUE THREAD

**Issue by flyzxm5177** [neuralmagic/sparseml#1502]
**Describe the bug**
I used `pip install sparseml-nightly` to make `sparseml.ultralytics.train` available, but I got a error after running
```
sparseml.ultralytics.train --task segment --model yolov8n-seg.yaml --pretrained \
                             --epochs 30 --batch 32  --name sparseml_test \
```
In addition, even though i set  the `-pretrained` , it didn't work.
How to fix it ? Thanks!

**Errors**
![image](https://user-images.githubusercontent.com/36351639/229285115-1fc95127-bd98-4fd3-895a-55d44d08464c.png)

----------------------------------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/36351639/229285134-e16a9f07-b037-4e32-8e65-123d46264fcd.png)

**Comment by flyzxm5177** [comment]
> 1. For loading from pretrained weights, you can use the `.pt` version of the model instead `--model yolov8n-seg.pt`. This will download the weights from ultralytics assets and you should see a loading weights from checkpoint message
> 2. The cublas error is from too large of a batch size - try lowering the batch and that should go away.

Thanks for your relpy, it works. I'd like to ask you one more question: Can I use `onnxruntime `or `openvino `to deploy sparsified yolov8 model after sparsifying models by `sparseml`. Looking forward to your reply!

**Comment by corey-nm** [comment]
@flyzxm5177 glad to hear! 👍 

Yep, if you run `sparseml.ultralytics.export` with a checkpoint from training, it'll export an onnx model for you to use. You can use this with our [deepsparse engine](https://github.com/neuralmagic/deepsparse) which will be much faster than onnxruntime/openvino (but yes you can use with onnxruntime/openvino since it's an onnx model).

We have yolov8 integrated into deepsparse, you can see some documentation on it here: https://github.com/neuralmagic/deepsparse/tree/main/src/deepsparse/yolov8

Will close this out for now, feel free to open another issue with more questions! And good luck 👍
