### ISSUE TITLE
Question on quantization size 

### ISSUE THREAD

**Issue by rajuptvs** [neuralmagic/sparseml#1854]
Hey Team, First of all thank you for all your wonderful work on quantizing models for the community.

I have some questions on quantization using sparseml and sparsezoo. I have been trying to perform Sparse Transfer Learning With a Custom Dataset mainly using yolov8s model as below

``` CLI
!sparseml.ultralytics.train \
  --model "zoo:cv/detection/yolov8-s/pytorch/ultralytics/coco/pruned65-none" \
  --recipe "zoo:cv/detection/yolov8-s/pytorch/ultralytics/voc/pruned65_quant-none" \
  --data /content/datasets/Sphero-Robot-detection-8/data.yaml \
  --recipe_args '{"num_epochs":15, "qat_start_epoch": 10, "observer_freeze_epoch": 12, "bn_freeze_epoch": 12}' \
  --batch 8
```

My main question is that usual .pt files of yolov8s models before and after training are of the size in range of 20-30 MB, but when using the above recipe, the model that is getting downloaded are of the size in the range of 120 - 130 MB, I was under the impression that models being quantized and pruned, should usually of smaller sizes in the range of 6-8 MB as shown in Zoo. 

Am I doing something wrong or is this usual? 

Thanking you in advance, 
Raju

**Comment by bfineran** [comment]
Hi @rajuptvs, the saved checkpoints from the sparseml script will be a bit larger than the original model for two reasons 
1. quantization aware training is still done using FP32 values instead of the integer representation to allow for easy backpropagation, so besides not decreasing the precision during training here we also increase size on the order of the model to track the quantization params
2. Because these are the full checkpoints, the optimizer state is saved as well which adds additional overhead, this is so the checkpoint can be used for further finetuning. The starting state likely has this stripped out (you can as well by runnning `del state["optimizer"]` and re-saving.

To get the model to full compressed size - you should export to ONNX using our `sparseml.ultralytics.export_onnx` script which will fold the QAT weights into a fully quantized graph at its compressed size

**Comment by jeanniefinks** [comment]
Hello,
We are going to go ahead and close out this issue. Please let us know if you have further questions on this specific topic; we're happy to help.

Jeannie / Neural Magic
