### ISSUE TITLE
4-core machine benchmarking results

### ISSUE THREAD

**Issue by OrkhanHI** [neuralmagic/sparseml#341]
Hi,

I am testing ResNet-50 benchmark on a 4-core `c5.2xlarge` instance. I could not find the results on the web-page.

Are the results on attached files are correct?

If this is correct, does this mean that the effect of sparse software is better on more core CPU machines (ex., 24 cores) than in small CPU core machines?
 

Thank you in advance. 

`Batch 1`
![4_cores_batch_1](https://user-images.githubusercontent.com/46919226/127472146-d86629c7-ca5e-451b-aadf-fca4eba14179.png)

`Batch 64`
![4_cores_batch_64](https://user-images.githubusercontent.com/46919226/127472141-e90c5f29-3b25-4ce6-9809-0efc8e383b78.png)

**Comment by mgoin** [comment]
Hi there. So you will see additional speedup in proportion to the number of cores you have available for sparse algorithms, up to a certain point where you become limited by memory bandwidth. 

In your case however I think you are talking about the pruned INT8 results being slower than the pruned FP32 results. This is because the smaller `c5.2xlarge` instance does not have the same instruction set support (mainly VNNI for INT8 operations) as the larger `c5.12xlarge`

I added a warning for when this situation occurs in https://github.com/neuralmagic/deepsparse/pull/165 , thanks for finding this issue!

**Comment by jeanniefinks** [comment]
Hi @OrkhanHI 
The linked PR submitted by my colleague has been merged. Thanks again for spotting this issue. It looks like you have no further comments so we'll close this issue out. If you have further comments related to this topic, please re-open the issue. 
Keep the feedback coming as we always enjoy hearing from users and your use cases.

Jeannie / Neural Magic
