### ISSUE TITLE
Question : Is latest yolov5 version compatible with sparsification ? 

### ISSUE THREAD

**Issue by MattVAD** [neuralmagic/sparseml#416]
More precisely, the version number 6. 
Thnx in advance if you've already try !

**Comment by markurtz** [comment]
Hi @MattVAD, we haven't migrated to the v6 code improvements yet, but it is on our list to complete over the next week or two. We'll update here once this is completed so you can try it out!

**Comment by MrinalJain17** [comment]
Hi @markurtz 

Any updates on this?

**Comment by ys31jp** [comment]
Hi, any update for the v6? Thanks

**Comment by markurtz** [comment]
Hi @MattVAD  @MrinalJain17 and @ys31jp, unfortunately, this fell down in priority for us currently due to a push we're doing for BERT models support. It is still active on our backlog and we are hoping to get to it after our next release in mid-January. With this, we'll be prioritizing using the next iteration YOLOv5 models to get even better recovery and performance. We'll keep this updated as we progress.

Thanks,
Mark

**Comment by GODGANG4885** [comment]
Hi @markurtz 
Any updates on this?
I am eagerly waiting for your update

**Comment by markurtz** [comment]
Hi @GODGANG4885, thanks for following up on this. We're roughly 4 weeks out (2 sprint cycles) from getting this worked in. I will update once we've started and code begins landing for early testers.

Thanks,
Mark

**Comment by jeanniefinks** [comment]
Hello @GODGANG4885 

 Support for this is coming in release 0.12 now ~second half of April. We will update here once we have something usable and landed on the nightly release as well. 

Best wishes! Jeannie / Neural Magic

**Comment by MrinalJain17** [comment]
@markurtz Thanks for the update. I'm excited to explore and try the new recipes (hopefully in the next few weeks).
