### ISSUE TITLE
Consider not installing sparseml from setup_integration scripts 

### ISSUE THREAD

**Issue by eldarkurtic** [neuralmagic/sparseml#425]
**Describe the bug**
Installing `sparseml` while setting up integrations overrules existing `sparseml` installation. For example, if I have `sparseml` installed in editable mode (`pip install -e`) and I want to setup integration with huggingface-transformers, this line https://github.com/neuralmagic/sparseml/blob/4fe5e44dba97c0cb3f4b4994dcf0eae80a350e1e/integrations/huggingface-transformers/setup_integration.sh#L12 would make my current `sparseml` installation obsolete. I think the same would happen if I had `sparseml` installed in the normal way (non editable), but with a version that is not the latest published at pip. 

**Expected behavior**
To still have/use the same `sparseml` version I had before running `setup_integration.sh` scripts.

**Potential fix**
I think a reasonable assumption would be that `sparseml` is already installed before trying to set any additional integration, so `pip install sparseml` could be removed from `setup_integration.sh` scripts.

**Comment by markurtz** [comment]
Hey @eldarkurtic, we want to make the assumption for anyone coming in that it will work out of the box by running the setup_integration.sh. I would be worried about users not knowing that they need to have SparseML installed before running the integration. The specific issue that's happening here is the local install installs the nightly version rather than the official version so the namespace for the package is slightly different and they can end up conflicting. 

In the future, though, we do want to remove the SparseML install in the integration scripts and move them out to the requirements for the forked repositories. We'll keep this open until those changes have landed and then revisit to see if we're still seeing the same issues.

**Comment by eldarkurtic** [comment]
Yes, having SparseML in requirements for forked repos would be a nice solution.

**Comment by markurtz** [comment]
Sounds good, thanks @eldarkurtic, we'll pick this up for our 0.10 release to standardize on this approach.

**Comment by jeanniefinks** [comment]
Hi @eldarkurtic 
We have removed the setup_integration approach and now have pulled in the transformers integration as part of the sparseml installation. Therefore, any local install will now respect the changes without overriding.
