### ISSUE TITLE
【question】Why my yolov5s model is 80MB after pruned？

### ISSUE THREAD

**Issue by mx2013713828** [neuralmagic/sparseml#469]
I followed this：
https://github.com/neuralmagic/sparseml/blob/main/integrations/ultralytics-yolov5/tutorials/sparsifying_yolov5_using_recipes.md
and I get a big model more than 80M size.

**Comment by rahul-tuli** [comment]
Hi @mx2013713828 could you share which model stub did you use for your flow?

**Comment by Ankur-singh** [comment]
I am facing the same issue. I followed the steps from this tutorial : https://github.com/neuralmagic/sparseml/blob/main/integrations/ultralytics-yolov5/tutorials/yolov5_sparse_transfer_learning.md

I particular, I ran the following command:
```bash
python train.py --data voc.yaml --cfg ../models/yolov5s.yaml --weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned-aggressive_96?recipe_type=transfer --hyp data/hyp.finetune.yaml --recipe ../recipes/yolov5.transfer_learn_pruned.md
```

at the end, I am getting a model (`best.pt` file) which is 40+ MBs in size. And on the contrary, when I ran the command for baseline YOLOv5s transfer learning, my model (`best.pt` file) size is ~13 MB. 

- command used for **Baseline YOLOv5s transfer learning** -> model size ~13MB
```bash
python train.py --data voc.yaml --cfg ../models/yolov5s.yaml --weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/base-none --hyp data/hyp.finetune.yaml --epochs 50

```

- command used for **YOLOv5s Pruned transfer learning** -> model size ~40MB
```bash
python train.py --data voc.yaml --cfg ../models/yolov5s.yaml --weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned-aggressive_96?recipe_type=transfer --hyp data/hyp.finetune.yaml --recipe ../recipes/yolov5.transfer_learn_pruned.md

```

**Comment by mx2013713828** [comment]
> Hi @mx2013713828 could you share which model stub did you use for your flow?

thanks for your reply.
I followed this tutorial:
[sparsifying_yolov5_using_recipes.md](https://github.com/neuralmagic/sparseml/blob/main/integrations/ultralytics-yolov5/tutorials/sparsifying_yolov5_using_recipes.md).
and I used this command:
`python train.py --cfg ../models/yolov5s.yaml --weights "" --data coco.yaml --hyp data/hyp.scratch.yaml`
and
`python train.py --cfg ../models/yolov5s.yaml --weights PATH_TO_COCO_PRETRAINED_WEIGHTS --data coco.yaml --hyp data/hyp.scratch.yaml --recipe ../recipes/yolov5s.pruned.md`.
But got a 80M size model
![Screenshot from 2021-11-24 23-14-26](https://user-images.githubusercontent.com/16423859/143265307-690a12d8-2395-40c8-87ad-552e8054325c.png)
.

**Comment by mx2013713828** [comment]
> Hi @mx2013713828 could you share which model stub did you use for your flow?

Sorry, because of an accident in the family, I did not reply in time.
Anyway,thanks for your reply.

**Comment by mx2013713828** [comment]
> I am facing the same issue. I followed the steps from this tutorial : https://github.com/neuralmagic/sparseml/blob/main/integrations/ultralytics-yolov5/tutorials/yolov5_sparse_transfer_learning.md
> 
> I particular, I ran the following command:
> 
> ```shell
> python train.py --data voc.yaml --cfg ../models/yolov5s.yaml --weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned-aggressive_96?recipe_type=transfer --hyp data/hyp.finetune.yaml --recipe ../recipes/yolov5.transfer_learn_pruned.md
> ```
> 
> at the end, I am getting a model (`best.pt` file) which is 40+ MBs in size. And on the contrary, when I ran the command for baseline YOLOv5s transfer learning, my model (`best.pt` file) size is ~13 MB.
> 
> * command used for **Baseline YOLOv5s transfer learning** -> model size ~13MB
> 
> ```shell
> python train.py --data voc.yaml --cfg ../models/yolov5s.yaml --weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/base-none --hyp data/hyp.finetune.yaml --epochs 50
> ```
> 
> * command used for **YOLOv5s Pruned transfer learning** -> model size ~40MB
> 
> ```shell
> python train.py --data voc.yaml --cfg ../models/yolov5s.yaml --weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned-aggressive_96?recipe_type=transfer --hyp data/hyp.finetune.yaml --recipe ../recipes/yolov5.transfer_learn_pruned.md
> ```

Oh...
good news:happy to know I am not alone. hah
bad news:I still haven't solved this problem. : (

**Comment by mx2013713828** [comment]
> I am facing the same issue. I followed the steps from this tutorial : https://github.com/neuralmagic/sparseml/blob/main/integrations/ultralytics-yolov5/tutorials/yolov5_sparse_transfer_learning.md
> 
> I particular, I ran the following command:
> 
> ```shell
> python train.py --data voc.yaml --cfg ../models/yolov5s.yaml --weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned-aggressive_96?recipe_type=transfer --hyp data/hyp.finetune.yaml --recipe ../recipes/yolov5.transfer_learn_pruned.md
> ```
> 
> at the end, I am getting a model (`best.pt` file) which is 40+ MBs in size. And on the contrary, when I ran the command for baseline YOLOv5s transfer learning, my model (`best.pt` file) size is ~13 MB.
> 
> * command used for **Baseline YOLOv5s transfer learning** -> model size ~13MB
> 
> ```shell
> python train.py --data voc.yaml --cfg ../models/yolov5s.yaml --weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/base-none --hyp data/hyp.finetune.yaml --epochs 50
> ```
> 
> * command used for **YOLOv5s Pruned transfer learning** -> model size ~40MB
> 
> ```shell
> python train.py --data voc.yaml --cfg ../models/yolov5s.yaml --weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned-aggressive_96?recipe_type=transfer --hyp data/hyp.finetune.yaml --recipe ../recipes/yolov5.transfer_learn_pruned.md
> ```

I have solved this problem ,when I finished all epoch,the size of model become normal.
although,I dont know why

**Comment by Ankur-singh** [comment]
I am still getting the same issue. The models weights that I shared are the final ones i.e. after complete training. 

> I am facing the same issue. I followed the steps from this tutorial : https://github.com/neuralmagic/sparseml/blob/main/integrations/ultralytics-yolov5/tutorials/yolov5_sparse_transfer_learning.md
> 
> I particular, I ran the following command:
> 
> ```shell
> python train.py --data voc.yaml --cfg ../models/yolov5s.yaml --weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned-aggressive_96?recipe_type=transfer --hyp data/hyp.finetune.yaml --recipe ../recipes/yolov5.transfer_learn_pruned.md
> ```
> 
> at the end, I am getting a model (`best.pt` file) which is 40+ MBs in size. And on the contrary, when I ran the command for baseline YOLOv5s transfer learning, my model (`best.pt` file) size is ~13 MB.
> 
> * command used for **Baseline YOLOv5s transfer learning** -> model size ~13MB
> 
> ```shell
> python train.py --data voc.yaml --cfg ../models/yolov5s.yaml --weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/base-none --hyp data/hyp.finetune.yaml --epochs 50
> ```
> 
> * command used for **YOLOv5s Pruned transfer learning** -> model size ~40MB
> 
> ```shell
> python train.py --data voc.yaml --cfg ../models/yolov5s.yaml --weights zoo:cv/de
> ```

**Comment by mx2013713828** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by markurtz** [comment]
Hi @Ankur-singh and @mx2013713828 , could you use the `torch.load` function to load the saved state dict into a Python object and report back the keys that are stored in there? We believe the issue here is that a non-finalized checkpoint is being used after training rather than the finalized one. The finalized checkpoint strips out things like the optimizer state dict, EMA model state dict, etc to reduce the size to just the deployable weights. Additionally, could you try and run the [following function](https://github.com/neuralmagic/yolov5/blob/63b9a73e8f650b9fa908fa2a3c45b6f8f9a0dcc4/utils/general.py#L581) on your checkpoint and see if that fixes the size issue (this will strip that extra information).

A few other notes to call out with this from our side as well:
- Most model file formats do not support sparsity for file size compression and especially sparsity + quantization, so to realize the compression of these models we recommend running a compression algorithm such as gzip over the top of the files.
- If quantization is applied, this will also incur a slight size penalty for the files since this is the quantization training graph that is saved rather than the inference graph. To export the inference graph follow the steps in the next bullet.
- We also recommend exporting to ONNX for deployment with these models and applying a compression algorithm such as gzip on top. An example of this flow can be found in our sparse transfer learning tutorial [here](https://github.com/neuralmagic/sparseml/blob/main/integrations/ultralytics-yolov5/tutorials/yolov5_sparse_transfer_learning.md#exporting-for-inference). This will correct the model file and its size for export and store it in ONNX which is generally a more robust deployment format that can be used with many different deployment engines such as DeepSparse.

Thanks,
Mark

**Comment by Abdulmalik0x** [comment]
Hi @markurtz, I'm facing the same issue, despite of using the same pretrained yolov5s model of yours from the model zoo.

errors msg:

Unexpected key(s) in state_dict: "model.0.conv.conv.weight",

the final generated model after training is of size 14.4, instead of 3.x as I've used the pruned optimized recipe

Your support please ..

**Comment by markurtz** [comment]
Hi @Abdulmalik0x, can you confirm which YOLOv5 repository you are using? Please be sure to use our forked repo as we have additional code built out on top of the original: https://github.com/neuralmagic/yolov5

**Comment by jeanniefinks** [comment]
Hello @Abdulmalik0x 
As it's been some time with no response, I am going to go ahead and close out this issue. However, if you wanted to continue the conversation, please re-open and add your response - we're happy to help! And if you haven't already, please do ⭐ our GitHub Repo sparseml - we ❤️ the community support!
Best, Jeannie / Neural Magic
