### ISSUE TITLE
speed

### ISSUE THREAD

**Issue by aimen123** [neuralmagic/sparseml#741]
the size of pruned and  not pruned is same --->    14.4M
the spedd of that is same ,too
What do I need to do to make it go fasteri in my computer?

**Comment by dbogunowicz** [comment]
Hey @aimen123.
Could you provide more details to help us identify the problem?

Which model are you referring to? Could you give us the name or a link? Is it one of our models from SparseZoo (https://sparsezoo.neuralmagic.com/)?
How are you running inference (are you running on GPU, CPU, or on CPU using our DeepSparse Engine?)

**Comment by aimen123** [comment]
@dbogunowicz  the code is Quantization-Aware Training？ why 2 epoch in the yolov5s.pruned_quantized.md

**Comment by dbogunowicz** [comment]
It would really help us if you could adhere to the bugs reporting standards described here: https://github.com/neuralmagic/sparseml/blob/main/CONTRIBUTING.md 
```
For bugs, include:

brief summary
OS/Environment details
steps to reproduce (s.t.r.)
code snippets, screenshots/casts, log content, sample models
add the GitHub label "bug" to your post
```

This way we are able to troubleshoot more efficiently. 

Thank y ou!

**Comment by markurtz** [comment]
Hi @aimen123, the PyTorch weight files and ONNX export files will remain the same size for pruning only. This is because the pruning is done in an unstructured way meaning that we are introducing 0's into the weight matrices rather than changing their shape. To realize the unstructured pruning for file sizes, you'll need to run a compression algorithm over the weights which will result in the smaller files. 

For example, try the following on a linux machine:
`tar -czvf model.onnx.tar.gz model.onnx`

**Comment by aimen123** [comment]
> Hi @aimen123, the PyTorch weight files and ONNX export files will remain the same size for pruning only. This is because the pruning is done in an unstructured way meaning that we are introducing 0's into the weight matrices rather than changing their shape. To realize the unstructured pruning for file sizes, you'll need to run a compression algorithm over the weights which will result in the smaller files.
> 
> For example, try the following on a linux machine: `tar -czvf model.onnx.tar.gz model.onnx`

ok

**Comment by jeanniefinks** [comment]
Closing out this older issue as there has been no further activity.
Regards, Jeannie / Neural Magic
