### ISSUE TITLE
Unable to train Yolov5 model from latest release

### ISSUE THREAD

**Issue by m-guise** [neuralmagic/sparseml#905]
I am trying to train a yolov5 model using the latest code release. 
I have already run the `pip install sparseml[torchvision]` command to install sparseml.

However if I run `sparseml.yolov5`, I am getting the following error `sparseml.yolov5: command not found`

Can you please clarify on how to train the model?

**Comment by KSGulin** [comment]
Hi @m-guise, in order to run a training command, you need to use the full command `sparseml.yolov5.train`. To run any of the other tasks (export, validation, onnx validation) you can use the command listed in the [readme](https://github.com/neuralmagic/sparseml/tree/main/src/sparseml/yolov5). For the full list of training args, you can run `sparseml.yolov5.train --help`

**Comment by m-guise** [comment]
@KSGulin 
Even with the full command, it is showing the same error. Can you specify from which directory do I need to run the command for training?
Also `sparseml.yolov5.train --help` is not working. Am I missing something?
