### ISSUE TITLE
RuntimeError:All supplied parameter names or regex patterns not found

### ISSUE THREAD

**Issue by JimmyW-11** [neuralmagic/sparseml#928]
when i use 
--cfg models/yolov5s.yaml 
--weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned_quant-aggressive_94?recipe_type=transfer \
--hyp data/hyps/hyp.finetune.yaml \
--recipe zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned-aggressive_96
i found this error, if this recipe cannot support the yolov5_v6.0 models? Thanks!

**Comment by KSGulin** [comment]
Hi @JimmyW-11, the existing recipes were developed for yolov5 (original) and only support that architecture at the moment. Our research team is actively working on new recipes for yolov5_v6 which we hope to release within the next couple of months. 

Note that the primary reason the recipes are incompatible is because the recipes targets specific layers to be pruned to a certain %. You can get around this by manually setting the layers you want pruned in the recipe or simply using the keyword `_ALL_PRUNABLE__` for the params field to prune all layers. You can attain reasonable, but not quite SOTA results this way.
